WIP l10n_br_account: seems we have a regression sinc the last fiscal_decorator fixes:
When importing n NFe without this:

    self._perform_onchange([field])
  File "/opt/odoo/odoo/tests/common.py", line 2136, in _perform_onchange
    result = record.onchange(self._onchange_values(), fields, spec)
  File "/opt/odoo/odoo/models.py", line 6305, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "/opt/odoo/odoo/models.py", line 6047, in _onchange_eval
    method_res = method(self)
  File "/mnt/data/odoo-addons-dir/l10n_br_account/models/account_move_line.py", line 548, in _onchange_price_subtotal
    line.update(line._get_amount_credit_debit())
  File "/mnt/data/odoo-addons-dir/l10n_br_account/models/account_move_line.py", line 570, in _get_amount_credit_debit
    amount_tax_included = self.amount_tax_included_from_tax_values
  File "/opt/odoo/odoo/fields.py", line 1043, in __get__
    self.compute_value(recs)
  File "/opt/odoo/odoo/fields.py", line 1199, in compute_value
    records._compute_field_value(self)
  File "/opt/odoo/odoo/models.py", line 4089, in _compute_field_value
    odoo.fields.determine(field.compute, self)
  File "/opt/odoo/odoo/fields.py", line 81, in determine
    needle = getattr(records, needle)
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/odoo/odoo/http.py", line 652, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/http.py", line 317, in _handle_exception
    raise exception.with_traceback(None) from new_cause
AttributeError: 'account.move.line' object has no attribute '_compute_amount_tax_from_tax_values'